<?php
echo '<!DOCTYPE html>';
echo '';
echo '<html lang="en" xmlns="http://www.w3.org/1999/xhtml">';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<title>Welcome! :D</title>';
echo '</head>';
echo '';
echo '<body bgcolor="#FFFAF0">';
echo '<h1 style="background-color:Violet;">';
echo 'Hola a todos! Esta es una pagina para la materia de Practica de Desarrollo de Sistemas II. Estas en AwardSapace';
echo '</h1>';
echo '';
echo '<p style="border: 2px solid Aquamarine;">';
echo 'Otros Hosts:';
echo '<br><a href="https://denilomas.000webhostapp.com/">000WebHost</a>';
echo '<br><a href="https://denilomas.dennxa.repl.co">Replit</a>';
echo '<br><a href="http://denilomas.atwebpages.com/">AwardSpace</a>';
echo '</p>';
echo '';
echo '<p style="border:2px solid Violet;">';
echo 'Sobre mi:';
echo '<br>Me llamo Denia, tengo 21 a;os y actualmente estudio Ingenieria en Sistemas de informacion.';
echo '<br>Me gusta: escuchar musica, jugar videojuegos, cocinar y ver peliculas.';
echo '<br>No me gusta: la guayaba jeje';
echo '</p>';
echo '';
echo '<div align="center">';
echo '<img src="img.jpeg" alt="yo" width="200">';
echo '';
echo '</div>';
echo '';
echo '';
echo '<p style="border:2px solid Gray;">';
echo 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ultrices eros in imperdiet rhoncus.';
echo 'Maecenas et quam placerat, facilisis sem ac, tincidunt urna.';
echo 'Praesent metus turpis, egestas in facilisis ac, placerat in eros.';
echo 'Proin imperdiet leo eu mi rhoncus rhoncus. Vestibulum porta';
echo 'laoreet dui, eu egestas erat lobortis ac. Aenean quis mauris tincidunt nibh congue hendrerit. Aenean id suscipit mi.';
echo '</p>';
echo '';
echo '<p style="border: 2px solid Chartreuse;">';
echo 'Datito extra:';
echo '<br>Mi grupo favorito se llama NCT y los sigo desde 2018 <3';
echo '<div align="center">';
echo '<img src="nct.jpg" alt="nct" width="500">';
echo '</div>';
echo '</p>';
echo '';
echo '</body>';
echo '</html>';
?>